### PR TITLE
Handling single model in sync method

### LINKED ISSUE #2395: `syncWithoutDetaching()` isn't accepting a single model as an argument
- Laravel Version: 9.13.0
- Laravel-mongodb Version: 3.9.0
- PHP Version: 8.0.17
- Database Driver & Version: MongoDB PHP, v5.0.6

### Description:
When passing a model instance to a `syncWithoutDetaching()` method, an exception is thrown.
This behaviour differs from cases with Laravel's Eloquent models, when a single model is accepted by this method.

### Steps to reproduce
*Let's use a `User` and a `Post` entity for this example*
1. Create a `Post` model
2. Create a `User` model with a one-to-many relation to `Post` one
3. Store a record of a single user in DB (without any related posts)
4. Store a record of a single post in DB
5. Pick a post record from a previous step via `Post` model
6. Try to assign this post to a user like this: `$user->posts()->syncWithoutDetaching($post);`

### Expected behaviour
An existing post record should be put in a relationship with a user record

### Actual behaviour
An exception is thrown instead:
```
Jenssegers\Mongodb\Relations\BelongsToMany::formatSyncList(): Argument #1 ($records) must be of type array, App\Models\Representative given
```

### PR DESCRIPTION
**Pull request by hans-thomas**
Hi, `sync` and `syncWithoutDetaching` methods now accept a single model as an argument.
Related issue (fix #2395) and PR (fix #2396).

### CODE REVIEW

**Comment by hans-thomas** [comment]
@GromNaN Can you please review this PR?

File: src/Relations/BelongsToMany.php [hunk 1]
```diff
@@ -117,6 +117,8 @@ public function sync($ids, $detaching = true)
 
         if ($ids instanceof Collection) {
             $ids = $ids->modelKeys();
```
Comment (GromNaN) [inline src/Relations/BelongsToMany.php:119]: I guess there is an other issue with this call. It should be `$ids = $this->parseIds($ids);` also. Otherwise it's getting the model `_id` instead of the `relatedKey`.

Do you want to add an other test with a customized `relatedKey`? That will require a new model class for tests, but will ensure we use the correct ID field.

**Review by GromNaN — APPROVED** [review]
Looks good. Thanks.

**Review by GromNaN — APPROVED** [review]
Thank you @hans-thomas

File: src/Relations/BelongsToMany.php (hunk 1 above)
Comment (hans-thomas) [reply src/Relations/BelongsToMany.php:119]: Sorry for the delay, I was super busy with other issues. I will add your requested tests in another PR later.
