### PR TITLE
Fix chunked order query bug

### LINKED ISSUE #3474: Incorrect sorting in MongoDB when using chunkById
- Laravel-mongodb Version: 12.47.0
- PHP Version: 8.4
- Database Driver & Version: 

### Description:
When using the `chunkById()` method with a model using the MongoDB driver, an incorrect sort query is generated with a duplicate `_id` key and a numeric key "0".

### Steps to reproduce
```php
Item::query()
    ->orderBy('id')
    ->chunkById(100, fn() => throw new \Exception('test'));
```

### Expected behaviour
The correct sort should look like this:
```json
{
  "find": "items",
  "filter": {
    "$and": [
      { "_id": { "$ne": null } },
      { "deleted_at": null }
    ]
  },
  "limit": { "$numberInt": "100" },
  "sort": {
    "_id": { "$numberInt": "1" }
  }
}
```

### Actual behaviour
```json
{
  "find": "items",
  "filter": {
    "$and": [
      { "_id": { "$ne": null } },
      { "deleted_at": null }
    ]
  },
  "limit": { "$numberInt": "100" },
  "sort": {
    "0": { "$numberInt": "1" },
    "_id": { "$numberInt": "1" }
  }
}
```

Issue: The sort section contains an incorrect key `"0"` along with _id.

### Root Cause
The problem arises from differences in the `orders` storage structure between Illuminate and MongoDB:

Illuminate: `orders` is an array of objects with `column` and `direction` keys
MongoDB: `orders` is an object (associative array)

In the `removeExistingOrdersFor()` method of the `Builder` class:

```php
protected function removeExistingOrdersFor($column)
{
    return (new Collection($this->orders))
        ->reject(fn ($order) => isset($order['column']) && $order['column'] === $column)
        ->values()
        ->all();
}
```

Problems:

* The `reject()` method doesn't filter orders correctly for MongoDB (since the data structure is different)
* Calling `values()` reindexes the array with numeric keys, causing the loss of original object keys in orders
* As a result, we get the key "0" instead of removing the existing sort

### PR DESCRIPTION
**Pull request by paulinevos**
Fix https://github.com/mongodb/laravel-mongodb/issues/3474

Illuminate's query builder ordering was conflicting with our own, resulting in incorrect ordering for chunked queries.

### Checklist

- [x] Add tests and ensure they pass

### CODE REVIEW

File: tests/Query/BuilderTest.php [hunk 1]
```diff
@@ -531,6 +532,16 @@ function (Builder $builder) {
                 ->orderBy('age', 1),
         ];
 
+        yield 'chunked ordering' => [
+            ['find' => [[], ['sort' => ['_id' => 1]]]],
+            function (Builder $builder) {
+                $builder->orderBy('id');
+                $builder->chunkById(2, fn($results, $page) => var_dump($page));
```
Comment (GromNaN) [inline tests/Query/BuilderTest.php]: Instead of testing `chunkById` which runs the query, you can call `$builder->forPageAfterId()` that configures the query builder without running it. That's closer to your fix.


```suggestion
                $builder->forPageAfterId();
```

File: src/Query/Builder.php [hunk 2]
```diff
@@ -685,6 +704,41 @@ public function orderBy($column, $direction = 'asc')
...
+                ->all();
+        }
+
+        // Our standard shape: associative ['column' => direction]
+        $column = (string) $column;
+
+        // Remove direct key
+        if (array_key_exists($column, $orders)) {
+            unset($orders[$column]);
+        }
```
Comment (GromNaN) [inline src/Query/Builder.php]: The condition is not necessary, you can remove an offset that is not set.
```suggestion
        unset($orders[$column]);
```

File: src/Query/Builder.php [hunk 3]
```diff
@@ -685,6 +704,41 @@ public function orderBy($column, $direction = 'asc')
...
+
+        // Also remove alias variant between 'id' and '_id' if present
+        if ($column === 'id' && array_key_exists('_id', $orders)) {
+            unset($orders['_id']);
+        } elseif ($column === '_id' && array_key_exists('id', $orders)) {
+            unset($orders['id']);
+        }
```
Comment (GromNaN) [inline src/Query/Builder.php]:
```suggestion
        if ($column === 'id') {
            unset($orders['_id']);
        } elseif ($column === '_id') {
            unset($orders['id']);
        }
```

File: tests/Query/BuilderTest.php (hunk 1 above)
Comment (paulinevos) [reply tests/Query/BuilderTest.php]: That worked perfect, thanks

File: tests/Query/BuilderTest.php [hunk 4]
```diff
@@ -1689,6 +1700,6 @@ private function getBuilder(bool $renameEmbeddedIdField = true): Builder
         $connection->method('getSession')->willReturn(null);
         $connection->method('getQueryGrammar')->willReturn(new Grammar($connection));
 
-        return new Builder($connection, null, $processor);
+        return (new Builder($connection, null, $processor))->from(Birthday::class);
```
Comment (GromNaN) [inline tests/Query/BuilderTest.php]: This change is not necessary.
```suggestion
        return new Builder($connection, null, $processor);
```

File: src/Query/Builder.php [hunk 5]
```diff
@@ -685,6 +704,39 @@ public function orderBy($column, $direction = 'asc')
...
+    protected function removeExistingOrdersFor($column): array
+    {
+        $orders = $this->orders ?? [];
+
+        // If orders are in the base shape (list of arrays with 'column'), mimic base behavior sans values()
+        if ($orders && array_is_list($orders) && isset($orders[0]) && is_array($orders[0]) && array_key_exists('column', $orders[0])) {
+            return (new Collection($orders))
+                ->reject(fn ($order) => isset($order['column']) && $order['column'] === $column)
+                ->all();
+        }
```
Comment (GromNaN) [inline src/Query/Builder.php]: The `_id`/`id` alias is not supported in that case here.

File: tests/Query/BuilderTest.php (hunk 4 above)
Comment (paulinevos) [reply tests/Query/BuilderTest.php]: Ah yeah still left over from before, whoops

**Review by GromNaN — APPROVED** [review]
